### ISSUE TITLE
plugins/knx/ : readonly in plugin.yaml problems

### ISSUE THREAD

**Issue by lgb-this** [smarthomeNG/smarthome#220]
(develop) I have the following code in my plugin.yaml:

```
knx:
    class_name: KNX
    class_path: plugins.knx
    host: 192.168.10.159
    port: 6720
    send_time: 600     # update date/time every 600 seconds, default none
    time_ga: 0/0/3
    date_ga: 0/0/2
    busmonitor: False  # log all knx messages, default false
    readonly: False    # don't write to knx bus, default false"
    instance: default
```

As soon as i enable the line with **readonly**, i get the info in the log-file, that KNX is readonly independant of the value i set in the line **readonly**. I tried True, False with or without apostrophe - it ignores the value and sets KNX to readonly.

**Comment by psilo909** [comment]
i pushed a fix to the develop branch of plugins folder, adding self.to_bool conversion to this attribute..

i am a little bit unsure if anyone ever tested the KNX plugin in readonly mode.

**Comment by lgb-this** [comment]
I get a crash with the new version:

```
2017-08-02  16:17:14 ERROR    Main         Plugin knx exception: 'module' object has no attribute 'KNX'
Traceback (most recent call last):
  File "/usr/local/smarthome/lib/plugin.py", line 90, in __init__
    plugin_thread = PluginWrapper(smarthome, plugin, classname, classpath, args, instance)
  File "/usr/local/smarthome/lib/plugin.py", line 130, in __init__
    exec("self.plugin = {0}.{1}.__new__({0}.{1})".format(classpath, classname))
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'KNX'

```

**Comment by psilo909** [comment]
what version did you have before? we rewrote parts of the plugin in the last weeks.. do you have newest version of smarthomeng running?

**Comment by lgb-this** [comment]
I pull always the newest release from the develop (main and plugins).

**Comment by psilo909** [comment]
just tried to configure readonly = True here and it is working.

**Comment by msinn** [comment]
The error message hints to an error in the plugin.conf / plugin.yaml file. Could you post that file (or at least the section that configures knx)?

**Comment by lgb-this** [comment]
I made a new git pull (develop) and i use this sequence in my plugin.yaml:

```
knx:
    class_name: KNX
#   class_path: plugins.knx
    class_path: plugins.aaknx
    host: 192.168.10.159
    port: 6720
    send_time: 600     # update date/time every 600 seconds, default none
    time_ga: 0/0/3
    date_ga: 0/0/2
    busmonitor: False  # log all knx messages, default false
#   readonly: False    # don't write to knx bus, default false"
#   readonly: True
    instance: default
```
When i enable one of the lines with readonly, i get always:

`2017-08-02  18:40:59 WARNING  Main         !!! KNX Plugin in READONLY mode !!! `
