### ISSUE TITLE
plugin network (develop): does not recevice udp-messages with plugin.yaml

### ISSUE THREAD

**Issue by lgb-this** [smarthomeNG/smarthome#223]
I'm on the latest develop in SmarthomeNG and the plugins (1.4.46a242f.dev).

I send udp-messages from a raspberry pi to my SmarthomeNG. The system works fine with my original plugin.conf:

```
[nw]
    class_name = Network
    class_path = plugins.network
    port = 2727
    udp = yes
```

I see the following logs in the debug-mode:

`2017-08-05  09:58:51 DEBUG    Main         Item Sensoren.Estrich.Estrich_Temperatur = 25.9 via UDP 192.168.10.158 None`

Now i moved to the plugin.yaml:

```
%YAML 1.1
---
nw:
    class_name: Network
    class_path: plugins.network
    port: 2727
    udp: yes
```

Now i don't get any messages into SmarthomeNG. The debug-mode does not show any error or upd-message coming in. Is see only:

```
2017-08-05  10:01:06 DEBUG    Main         Plugin: nw
2017-08-05  10:01:06 DEBUG    Main         Using arguments ['port', 'udp']
```
Any idea ?

**Comment by psilo909** [comment]
the conf - yaml converter in the  backend (developer mode) says:

nw:
    class_name: Network
    class_path: plugins.network
    port: 2727
    udp: 'yes'

**Comment by lgb-this** [comment]
Bingo ! The communication runs well now with

```
nw:
    class_name: Network
    class_path: plugins.network
    port: 2727
    udp: 'yes'
```

The file  smarthome/etc/plugin.yaml.default is very confusing:

```
# dlms:
#     class_name: DLMS
#     class_path: plugins.dlms
#     serialport: /dev/ttyO1
#     baudrate: 300    # default 300
#     update_cycle: 20    # default 20
#     use_checksum: no    # default no
#     reset_baudrate: no    # default no
# no_waiting: yes # default yes
```

No apostroph for dlms. In the same file for nw with apostroph:

```
# nw:
#     class_name: Network
#     class_path: plugins.network
#     ip: 0.0.0.0
#     port: 2727
#     http: 8765
#     tcp_acl:
#       - 127.0.0.1
#       - 192.168.0.34
#     udp: 'no'
# udp_acl: '*'
```

And in the file  plugins/network/README.md (develop) again not consistent:

```
nw:
    class_name: Network
    class_path: plugins.network
    # ip = 0.0.0.0
    # port = 2727
    tcp: 'yes'
    tcp_acl:
      - 127.0.0.1
      - 192.168.0.34
    # udp = no
    # udp_acl= *
```

Perhaps it would be very helpful to add a section about the yaml in the Wiki.

**Comment by bmxp** [comment]
I am sure you know about this article in the wiki https://github.com/smarthomeNG/smarthome/wiki/Configuration-Files ?

**Comment by lgb-this** [comment]
No. Thanks for the link. It would be very helpful, if the example files would follow this specification.

**Comment by lgb-this** [comment]
There is a hint with the boolean values in the wiki:

`YAML interpretiert bis inclusive Version 1.1 auch yes und no als boolsche Werte. Deshalb müssen auch diese Werte in Quotes eingeschlossen werden. Es ist empfehlenswert nur true und false für boolsche Werte zu verwenden.`

I modified the plugin.yaml into:

```
nw:
    class_name: Network
    class_path: plugins.network
    port: 2727
    udp: 'true'
```

Result: upd-messages does not come into the system. Why ?
