### ISSUE TITLE
KNX plugin:problems with busmonitor

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#268]
My config:
knx:
    class_name: KNX
    class_path: plugins.knx
    busmonitor: on

Error message at startup:
 plugin 'knx': Invalid value 'True' in plugin configuration file for parameter 'busmonitor' -> using 'on' instead

Furthermore the busmonitor logging just doesn't work with the standard logging configuration. Something wrong there, too?

**Comment by bmxp** [comment]
Which version, develop or master?

**Comment by onkelandy** [comment]
SmartHomeNG 1.5.1.master (cc1288de)
Pretty sure it's in the develop, too.

**Comment by cstrassburg** [comment]
Bei mir funktioniert das wunderbar mit: 
```
 knx:
    class_name: KNX
    class_path: plugins.knx
    host: xxx.xxx.xxx.xxx
    port: 6720
    busmonitor: 'logger'
```

```

2018-08-13;07:27:21;;1.1.23;4/1/20;False;
2018-08-13;07:29:19;;1.1.23;4/1/21;00;
2018-08-13;07:29:35;;1.1.3;1/1/80;00;
2018-08-13;07:29:35;;1.1.2;1/1/81;False;
2018-08-13;07:29:44;;1.1.3;6/1/80;05fa;
2018-08-13;07:29:59;;1.1.3;6/1/80;01e7;
```

versuch aber zuerst das "on" in Apostroph zu setzen:   busmonitor: 'on'

**Comment by onkelandy** [comment]
Danke, Fehlermeldung verschwindet bei 'on'.
Ich hätte jetzt vermutet, dass ich dann einfach die entsprechenden Zeilen aus logging.yaml ent-kommentiere, also filters, handlers und loggers, damit ich selbst bestimmen kann, wie das Logging aussieht und in welches File geschrieben wird. Das funktioniert aber nicht so wie bei den anderen Plugins.

Was sehr wohl funktioniert ist, busmonitor: 'logger'
Hier wird ins entsprechende knx_busmonitor.log File geschrieben.

Im Zusammenhang mit den Möglichkeiten in logging.yaml scheint mir das Verhalten aber nicht wirklich schlüssig.

**Comment by cstrassburg** [comment]
Wenn der Parameter auf 'on' steht, werden die Bus-Nachrichten auf den Standard-Logger des Plugins geschrieben.  INFO Level
Bei False nur im DEBUG Level 
Hier gibt es keine Trennung, kann es technisch auch nicht geben.

Bei parameter 'logger' wird aus der logging.yaml der 'knx_busmonitor' Logger genommen und den kannst du konfigurieren. (Level INFO) 
```
       if busmonitor.lower() in ['on','true']:
            self._busmonitor = self.logger.info
        elif busmonitor.lower() in ['off','false']:
            self._busmonitor = self.logger.debug
        elif busmonitor.lower() == 'logger':
            self._bm_separatefile = True
            self._bm_format = "{0};{1};{2};{3}"
            self._busmonitor = logging.getLogger("knx_busmonitor").info
```
logging.yaml:
```
formatters:
  busmonitor_format:
    format: '%(asctime)s;%(message)s;'
    datefmt: '%Y-%m-%d;%H:%M:%S'

handlers:
  busmonitor_file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: busmonitor_format
    when: midnight
    backupCount: 7
    filename: ./var/log/knx_busmonitor.log

loggers:
    knx_busmonitor:
       level: INFO
       handlers: [busmonitor_file ]

```
