### ISSUE TITLE
plugin.yaml parameter api-methods defining Plugin methods for external reuse

### ISSUE THREAD

**Issue by walldi** [smarthomeNG/smarthome#272]
A parameter in the plugin metadata file plugin.yaml file, that lists all methods, the plugin want's to export as API.
Could be uses by blockly plugin to add usefull plugin APIs to the ToolBox.
(Also webservice plugin could export such methods as REST API? )

hypothetisches Beispiel für das knx-Plugin: 
```
api-methods:
    groupwrite:
         parameters:
            - ga: str
            - payload: num
            - dpt: str
            - flag: str='write'
         returns: num
```

**Comment by psilo909** [comment]
i also discussed this for autocomplete of codemirror in backend - would be a good thing. currently i am using the following code to reflect a plugins ap, to be exported with plugins.json:

```
    @cherrypy.expose
    def plugins_json(self):
        """
        returns a list of plugin names (from config) as json structure
        """
        not_allowed_functions = ['__init__', 'parse_item', 'parse_logic', 'update_item', 'init_webinterface',
                                 'init_webinterfaces']
        plugin_list = []
        for x in self.plugins.return_plugins():
            if isinstance(x, SmartPlugin):
                plugin_config_name = x.get_configname()
            else:
                plugin_config_name = x._configname

            #plugin_list.append(plugin_config_name)

            for func_name in inspect.getmembers(x, predicate=inspect.ismethod):
                if self.get_class_that_defined_method(func_name[1]) is not None:
                    class_name = self.get_class_that_defined_method(func_name[1]).__name__
                    if 'SmartPlugin' not in class_name and func_name[0] not in not_allowed_functions and not func_name[
                        0].startswith('_'):
                        plugin_list.append(plugin_config_name + "." + func_name[0]+str(inspect.signature(func_name[1])))

        return json.dumps(plugin_list)

    def get_class_that_defined_method(self, meth):
        if inspect.ismethod(meth):
            for cls in inspect.getmro(meth.__self__.__class__):
                if cls.__dict__.get(meth.__name__) is meth:
                    return cls
            meth = meth.__func__  # fallback to __qualname__ parsing
        if inspect.isfunction(meth):

            # Check to make sure the method has a "qualname"
            if not getattr(meth, '__qualname__', None):
                return None

            cls = getattr(inspect.getmodule(meth),
                          meth.__qualname__.split('.<locals>', 1)[0].rsplit('.', 1)[0])
            if isinstance(cls, type):
                return cls
        return None  # not required since None would have been implicitly returned anyway
```

**Comment by psilo909** [comment]
![unbenannt-1](https://user-images.githubusercontent.com/15831643/44455718-01308280-a5ff-11e8-9c7c-e66fa3c2f51c.png)

**Comment by smaiLee** [comment]
Couldn't this be extracted from Python class?
IMHO it is annoying for plugin developers if this has to be defined redundant.

**Comment by walldi** [comment]
Yes, I've seen this. But here also, I think: 

> explicit is better than implicit...

**Comment by psilo909** [comment]
@smaiLee see my comments

**Comment by psilo909** [comment]
> explicit is better than implicit...

yes i agree, but this will get a HUGE workload and a todo for ALL plugins (including the smartplugin migration, which is not neccessary with my approach)

**Comment by smaiLee** [comment]
Isn't the method def explicit? It's just a redundancy of exact same information (except the type, but python has decided to not be strongly typed, so untyped parameters are a general issue).
I think redundancy is always a possible source for errors.

But a util or a method in SmartPlugin could be helpful to return this information. Otherwise there's a new redundancy by multiple plugins implementing this (differently).

**Comment by psilo909** [comment]
@smaiLee if we add this to new admin interface, it will be at a central position of smarthomeng (admin interface is no plugin anymore)

**Comment by psilo909** [comment]
or we add a function to the smartplugin, "reflecting" its api.. but i would favor a central JSON url and support for non SmartPlugins

**Comment by psilo909** [comment]
i also thought about a tag at each function that shall be exported, like 

@shapi
def plugin_api_func1(self):
...

but i am not sure if that can be used for our purpose?

**Comment by walldi** [comment]
@psilo909 I don't think so. We don't want to add functionality to the methods.

My idea was: if the metadata file plugin.yaml describes, what a plugin can do, than the API methods should be included for completeness.

**Comment by psilo909** [comment]
by the way: i see, that in my implementation functions with a leading _ are already ignored. supose that's internal to "inspect"

**Comment by msinn** [comment]
When placing that info in the plugin.yaml, it could be used for generating the documentation too. Like the information for parameters and item attributes isinluded in the Plugin documentation inwww.smarthomeNG.de/user. That would be a next step to get rid of the readme.md.

**Comment by msinn** [comment]
I am for explicit for another reason: many plugins have methods that dont begin with an underline (which woul declare them a private) I don‘t want them listed. On the other hand, there are not so many plugins that define functions for exterior use. So the effort needed to put the info into the plugin.yaml files isn‘t that high.

**Comment by smaiLee** [comment]
> When placing that info in the plugin.yaml, it could be used for generating the documentation too.
> [...] That would be a next step to get rid of the readme.md.
Well, that's a point. It seems reasonable to add more information to the plugin.yaml if plugin developers do not have to write a readme in return.

**Comment by smaiLee** [comment]
This issue inspired me for another entry in plugin.yaml:
Some plugins add methods to items (e.g. database/sqlite `series()` and `db()`).
They should also be added to plugin.yaml.
As existing methods or even sub-items with same name get overwritten, adding such a method has a special impact.
If they are in plugin.yaml a conflict could be checked and logged.

**Comment by msinn** [comment]
I think the section for the functions that are public available for a plugin could look like this:

```
plugin_functions:
    # Definition of function interface of the plugin

    <function_name>:
        type: str
        description:
            de: 'Adresse des HomeMatic Devices, welches über die HomeMatic CCU2 Zentrale angesteuert werden soll'
            en: 'Adress of the HomeMatic device that shall be controlled (through the HomeMatic CCU2 central unit)'

        parameters:
            <parametername_name>:
                type: str
                description:
                    de: '<Beschreibung des Parameters der Funktion>'
                    en: '<Description of the function''s parameter>'

```

Additionally the other attributes from parameter definitions could be used for the parameters (default:, valid_min, valid_max, valid_list).
