### ISSUE TITLE
Improvement: combine list entries when parsing item/struct yaml 

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#317]
I would recommend that attributes consisting of lists are (at least on demand) combined throughout all items/*.yaml and etc/struct.yaml files.

Assume multiple struct definitions of a plugin:
```
item_structs:
  struct1:
    eval_trigger:
        - item1

  struct2:
    eval_trigger:
        - item2
        - item3
```

When including theses structs in an item using:
```
struct:
    - plugin.struct1
    - plugin.struct2
```
it would be great if the resulting eval_trigger attribute included all list entries from both structs with the following result:
```
    eval_trigger:
        - item1
        - item2
        - item3
```

Same applies for general items that are re-configured in the item tree I guess. Optionally the list entry could get an additional info like ", append" though that might make things even more complicated ;)
