### ISSUE TITLE
Struct not reliable

### ISSUE THREAD

**Issue by henfri** [smarthomeNG/smarthome#336]
Hello,

I have a problem using structs:

struct.yaml:
```
SteckdoseFunk:
    type: bool
    knx_dpt: 1
    influx: true
    mqtt_topic_in:  stat/gosundXX/POWER
    mqtt_topic_out: cmnd/gosundXX/power
    alexa_name: Template
    alexa_actions: "TurnOn TurnOff"
    alexa_device: XXXX
    alexa_description: XXXX
    hilfs_item:
      type: dict
      mqtt_topic_in:  tele/gosundXXX/SENSOR
      on_change: 
        - ..Leistung = value['ENERGY']['Power']
        - ..Scheinleistung= value['ENERGY']['ReactivePower']
        - ..Factor=value['ENERGY']['Factor']
        - ..Strom=value['ENERGY']['Current']
        
    Leistung:
      type: num
      influx: true
    Scheinleistung:
      type: num
    Factor:
      type: num
    Strom: 
      type: num
```

and then I am using it an an item.yaml:
```
Funk:
    SteckdoseFunk3:
        struct: SteckdoseFunk
        mqtt_topic_in:  stat/gosund3/POWER
        mqtt_topic_out: cmnd/gosund3/power
        alexa_name: Funkdose 3
        alexa_device: Funkdose_3
        alexa_description: Funkdose 3
        struct: uzsu.child
        hilfs_item:
          mqtt_topic_in:  tele/gosund3/SENSOR
```
I have two problems here:
1) Originally I had the strut: uzsu.child in the first code snippit  (so I was using a struct (the one of the uzsu plugin) inside my userdefined one). This did not work. I accept that this does not work, and that is not why I open this issue, but I think it is worth mentioning.
2)  the `alexa_actions: "TurnOn TurnOff"` does not turn up in sh.py. The other attributes do.

Greetings,
Hendrik

**Comment by onkelandy** [comment]
You have to use struct with a list!!!!
Struct:
   - xyz
   - uzsu.child

**Comment by henfri** [comment]
Oh, I was not aware. 
What is the reason?

**Comment by henfri** [comment]
It seems to have fixed my problem
Still i would like to understand the reason.
Especially why it partially works (why does the "hilfsitem") exist. Why does the uzsu item exist (but not work properly)

**Comment by henfri** [comment]
Hello,

unfortunately, this did not reliably fix my issue. 
The problem still exists with this setup:

```
Funk:
    SteckdoseFunk3:
        struct: 
            - SteckdoseFunk
        mqtt_topic_in:  stat/gosund3/POWER
        mqtt_topic_out: cmnd/gosund3/power
        alexa_name: Funkdose 3
        alexa_device: Funkdose_3
        alexa_description: Funkdose 3
        alexa_actions: "TurnOn TurnOff"
        struct: 
          - uzsu.child
        hilfs_item:
          mqtt_topic_in:  tele/gosund3/SENSOR
```

Why did I write that the problem was fixed? 

Well, I thought it was. The Item was complete after me changing the definition from

`        struct:  uzsu.child
`

to:

```
        struct: 
          - uzsu.child
```
And restarting. But I now think that the restart fixed it.
The problem could appear after some time. 
I also have this impression from this: https://knx-user-forum.de/forum/supportforen/smartvisu/1441665-no-uzsu-data-available-in-item-x-uzsu-for-widget-undefined 
Here, I use the same Item and the Visu works after a restart -for a while. And then it stops workin.

How can I further debug this problem?

Greetings,
Hendrik

**Comment by onkelandy** [comment]
You still use struct attribute twice. Please try it with this item (and try it without the mqtt and alexa attributes)
```
Funk:
    SteckdoseFunk3:
        struct: 
            - SteckdoseFunk
            - uzsu.child
        hilfs_item:
          mqtt_topic_in:  tele/gosund3/SENSOR
```
