### ISSUE TITLE
Feature request: adjust log message for log_change item attribute

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#373]
The plugin operationlog allows some mapping of values to be written in a separate log file. As the logging.yaml is very powerful almost all functions of the plugin are obsolete. Anyhow, some options for the log_change attribute would be nice.

As discussed on Gitter I suggest something like this:
```
log_text: f"{'Person A' if value == 1 else 'Person B' if value == 2 else 'Person C'} ist zuhause"
log_level: "DEBUG" if value <=2 else "ERROR" if value > 2
```

Of course it's also possible to refer to a helper item for the log text like this (as suggested by msinn) though I think the direct solution is easier and cleaner. Maybe I also misunderstood the idea with the helper item?
```
log_text_item: .item_logtext.property.value
log_level: "DEBUG" if value <=2 else "ERROR" if value > 2

item_logtext:
    type: str
    eval: f"{'Person A' if value == 1 else 'Person B' if value == 2 else 'Person C'} ist zuhause"
```

I'm willing to test some code as soon as it's clear how to proceed with the extra attributes.
