### ISSUE TITLE
Visu subscription of a memory log activates sending of env.core.log

### ISSUE THREAD

**Issue by onkelandy** [smarthomeNG/smarthome#595]
```
handlers:
    memory_warn:
        (): lib.log.ShngMemLogHandler
        logname: memory_warn
        maxlen: 60
        level: WARNING
        filters: [stateengine, roborock, roborock_2, standby]
root:
    level: WARNING
    handlers: [shng_warnings_file, memory_warn]
```

and 
```
{{ status.log('', 'memory_warn', 20) }}
```
results in correct subscription of the memory log on loading the visu page. However, as soon as the log gets updated (new entry added), the smartvisu also receives data from env.core.log which results in a console error. Maybe websocket exceptions also result from this behaviour or it's just a "cosmetic" issue..?

@wvhn could confirm that behaviour.
